name: Build EXE for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pdfplumber

      - name: Crear el ejecutable con PyInstaller
        run: |
          pyinstaller --onefile --windowed app.py

      - name: Subir artefacto (.exe)
        uses: actions/upload-artifact@v3
        with:
          name: App-Windows
          path: dist/app.exe
